version: "2"
services:
  dashboard:
    build: .
    image: capgemini-invent-ide/dashboard
    container_name: dashboard
    ports:
      - 8050:8050
    volumes:
      - .:/opt/working
    entrypoint: python /opt/working/app.py